const streetSuffixes = [
  "Avenue",
  "Boulevard",
  "Circle",
  "Court",
  "Drive",
  "Extension",
  "Road",
  "Street",
  "Way",
  "Lane",
  "Parkway",
  "Place",
  "Square",
  "Trail",
  "Loop",
];
const streetPrefixes = [
  "North",
  "East",
  "West",
  "South",
  "Old",
  "New",
  "Upper",
  "Lower",
  "Central",
  "Upper East",
  "Upper West",
  "Lower East",
  "Lower West",
  "Upper North",
  "Upper South",
  "Lower North",
  "Lower South",
  "Main",
  "First",
  "Second",
  "Third",
  "Fourth",
  "Fifth",
  "Sixth",
  "Seventh",
  "Eighth",
  "Ninth",
  "Oak",
  "Maple",
  "Elm",
  "Cedar",
  "Pine",
  "Hickory",
  "Willow",
  "Ash",
  "Dogwood",
  "Chestnut",
  "Mulberry",
  "Magnolia",
  "Spruce",
  "Tulip",
  "Upland",
  "Beech",
  "Holly",
  "Redwood",
  "Oklahoma",
  "Opal",
  "Orchard",
  "Virginia",
  "Vine",
  "Vineyard",
  "Queen",
  "Quail",
  "Union",
  "University",
  "Valley",
  "Primrose",
  "Park",
  "Lake",
  "Yuanita",
  "Yale",
  "Mnolia",
  "Boone",
  "Yellowstone",
  "Yosemite",
  "Xenia",
  "Xotica",
  "Windsor",
  "Otter",
  "Horse",
  "Highland",
  "Trinity",
  "Eagle",
];

const randomStreetName = () => {
  /**
   * Return a random string from the streets array.
   * @return {string}
   */
  const streetPrefix =
    streetPrefixes[Math.floor(Math.random() * streetPrefixes.length)];
  const streetSuffix =
    streetSuffixes[Math.floor(Math.random() * streetSuffixes.length)];
  const streetName = `${streetPrefix} ${streetSuffix}`;
  return streetName;
};

module.exports = randomStreetName;
